#- name: Upgrade System
 # apt: update


- name: install software-properties-common
  apt: name=software-properties-common state=latest
- name: Add php repository
  apt_repository:
   repo: 'ppa:ondrej/php'

- name: Install PHP
  apt: name=php{{php_version}} state=latest

- name: Install PHP MB
  apt: name=php{{php_version}}-mbstring state=latest

- name: Install PHP XML
  apt: name=php-xml state=latest

- name: Install PHP EXT
  apt: 
    name:
      - unzip
      - php{{php_version}}-mysql
      - php{{php_version}}-curl
      - php{{php_version}}-gd
      - php{{php_version}}-xsl
      - php{{php_version}}-bcmath
      - php{{php_version}}-bz2
      - php{{php_version}}-intl
      - php{{php_version}}-dom
    state: latest

- name: install composer
  command: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

- name: install composer -1
  shell: HASH="$(wget -q -O - https://composer.github.io/installer.sig)"

- name: rename composer.phar to composer
  shell: php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

- name: make composer executable
  shell: sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer --version=2.3.10

- name: install apache2 server
  apt:
     name: apache2
     state: present
- name: install mysql server
  apt: 
     name: mysql-server
     state: latest

- name: checkout latest code from github
  git: >
    repo=https://github.com/devops4solutions/lavaral_project.git
    dest=/opt/{{ vhost_name }}
    force=yes
    accept_hostkey=yes

- name: copy lavarel project
  shell: sudo mv /opt/{{ vhost_name }} /var/www/html/

- name: Change permission
  shell: sudo chgrp -R www-data /var/www/html/{{ vhost_name }}/

- name: Change permission
  shell: sudo chmod -R 775 /var/www/html/{{ vhost_name }}/storage

- name: Remove default apache vhost config from sites-enabled
  file: name=/etc/apache2/sites-enabled/000-default.conf state=absent

- name: Create apache vhosts for  domain
  template: src=web.conf.j2 dest="/etc/apache2/sites-available/{{ vhost_name }}.conf" owner=www-data group=www-data mode=0644

- name: Update a2ensite
  command: a2ensite {{ vhost_name }}

- name: Enable the Apache rewrite module
  command:  a2enmod rewrite

  notify:
    - restart apache2
